stages:          # List of stages for jobs, and their order of execution
  - build

build-on-linux-job:
  image: ubuntu:18.04
  stage: build
  script:
    - apt-get update
    - apt-get install make build-essential libxi6 libxtst6 libfontconfig libfreetype6-dev libxcomposite1 libxrender1 libxrandr2 libasound2 libgssapi-krb5-2 libxcursor1 libnss3 libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev libxcb-util1 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 python3-pip -y
    - python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
    - python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - python3 -m pip install setuptools wheel
    - python3 -m pip install py7zr==0.16.1
    - python3 -m pip install aqtinstall==1.2.5
    - python3 -m aqt install 5.15.2 linux desktop -m qtwebengine -O /builds/ambition-echo/uestctools/Qt
    - /builds/ambition-echo/uestctools/Qt/5.15.2/gcc_64/bin/qmake
    - make
  artifacts:
    paths:
      - /builds/ambition-echo/uestctools/UestcTools
test:
  tags: arch
  stage: build
  script:
    - mkdir qt 