stages:          # List of stages for jobs, and their order of execution
  - build

build-on-linux-job:
  image: archlinux:latest
  stage: build
  script:
    - echo -e 'Server=https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    - pacman -Sy --noconfirm
    - pacman -S qt6-base qt6-webengine gcc gcc-libs clang make --noconfirm
    - qmake6
    - make
  artifacts:
    paths:
      - /builds/ambition-echo/uestctools/UestcTools
