name: Windows
on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  #windows编译
  Build-Windows:
    #运行平台
    name: Build on Windows
    runs-on: windows-2019
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          arch: 'win64_msvc2019_64'
          modules: qtwebengine
          target: 'desktop'
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      #3编译构建
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      #4打包部署
      - name: package
        run: |
          md D:/a/UestcTools/UestcTools/build
          copy D:/a/UestcTools/UestcTools/release/UestcTools.exe D:/a/UestcTools/UestcTools/build
          windeployqt.exe D:/a/UestcTools/UestcTools/build/UestcTools.exe
      #5打包成zip
      - name: To zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'build'
          filename: 'UestcTools_Windows.zip'
      #6上传artifact
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: UestcTools_Windows
          path: D:/a/UestcTools/UestcTools/build
          if-no-files-found: error
      #7发布release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: UestcTools_Windows.zip
          tag: ${{ github.ref }}
          overwrite: true